### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by a0yan**
Changing command which caused corrupt file error in bootstrap.ani

### CODE REVIEW

**Comment by ruessej** [comment]
This PR this problem: https://stackoverflow.com/a/70107291/16251630

**Comment by elwerene** [comment]
Having the command twice does not seem right to me!

**Comment by ruessej** [comment]
I only know that this fixes the problem with the bootstrap.ini

**Comment by elwerene** [comment]
Should be fixed by https://github.com/elwerene/libreoffice-convert/pull/78

**Pull request closed without merging**
