### PR TITLE
Expose parameter to override the tmp library options

### LINKED ISSUE #34: Ability to set the tmp directory
In environments such as Kubernetes where volumes are mounted to a specific directory, it would be ideal to set the root temp directory to the volume mount location.
Based on tmp's documentation `tmpdir` allows the option to override that.

### PR DESCRIPTION
**Pull request by a7i**
Fixes #34

### CODE REVIEW

**Comment by elwerene** [comment]
It feels strange to have arguments behind the callback argument. Could you change your merge request to provide a new method with e.g. a options Object which includes the tmpOptions, like this:
```
 exports.convertWithOptions = (document, format, filter, options, callback) => {
```

and in exports.convert you call it with some default options?

You are free to choose a name, `convertWithOptions` sounds like a objective-c method, not a ecmascript method :)

**Comment by a7i** [comment]
I agree @elwerene , did not want to break backwards compatibility. I will apply the changes per your suggestion.

**Comment by elwerene** [comment]
It will not break if you leave the signature of `exports.convert` intact ;)

**Comment by elwerene** [comment]
@a7i  Please put the `tmpOptions` into an `options` object so we have some space where we can introduce new options in the future!

**Comment by elwerene** [comment]
looks good to me!

**Comment by elwerene** [comment]
I published a new version 1.2.0. Thx @a7i

**Pull request merged**
