### PR TITLE
added -env:UserInstallation for multiple instance

### PR DESCRIPTION
**Pull request by bgorhoball**
This corresponds to [the comment on this pull request](https://github.com/elwerene/libreoffice-convert/pull/26#issuecomment-638730052)

### CODE REVIEW

**Comment by elwerene** [comment]
https://github.com/elwerene/libreoffice-convert/pull/26#issuecomment-639358441

**Comment by elwerene** [comment]
@bgorhoball  If you like, please send me your Name/Mail for the contributors info in package.json

**Comment by bgorhoball** [comment]
@elwerene thanks and it's grateful for me to contribute in this project!
Brian Chong bgorhoball@protonmail.com

**Comment by bgorhoball** [comment]
@elwerene thanks and it's grateful that I could contribute in this project!
Brian Chong bgorhoball@protonmail.com

**Pull request merged**
